### PR TITLE
Declaration of Independence from Right Click API

### PR DESCRIPTION
**Pull request by Vectorial1024**
Big if true.

As outlined in #9, and borrowing the analogy from #11, I now know enough about the door made by SirNukes that I can confidently use their door; the mod has been restructured to fully use SirNukes Mod Support API, thus totally eliminating the need of Right Click API. Beta releases from EgoSoft shall never scare me.

That said, the Fallback Mode is still there in case something really unexpected happened, but the probability of such things happening is now very small.

### CODE REVIEW

**Comment by Vectorial1024** [comment]
As usual, since this change is rather big, Imma leave this here for a while so I can review them later.

**Comment by FormBurden** [comment]
I'll test it out.

**Comment by FormBurden** [comment]
So how exectly is this going to work to assign non-combat ships to their rightful role in a fleet? I'm using this new update and whatever I do it actually assigns them to a defense role. Either I'm missing something on how to add them to their proper role or is the code still being implemented?

**Comment by Vectorial1024** [comment]
@FormBurden you may want to download again; f3aad1dfd14ff4df87c40fac86f92661f920806a fixes an awkward bug where the right click code is only loaded once per savegame. With that bug, you will never see the added [Trader >] or [Miner >] buttons when you load a save game after the save game itself has been loaded with the mod itself at least once.

**Comment by Vectorial1024** [comment]
Seeing there are no problems, will be merging this soon.

**Pull request merged**
